import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const globalFont = localFont({
    src: "../public/fonts/ModernTypewriter-zrOYw.ttf",
    variable: "--global-font",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${globalFont.className} antialiased`}>
                {children}
            </body>
        </html>
    );
}
